### ISSUE TITLE
Stories/Actions

### ISSUE THREAD

**Issue by lauradax** [ID-Start-Winter22/Turbo#10]
Brainstorming notwendig, was genau soll möglich sein, wo sind die Grenzen?
Darüber haben wir zwar im kleinen schonmal gesprochen, allerdings sollten wir das 1. nochmal genauer besprechen und 2. mit dem Issue zu "Ausflugszielen" verknüpfen.

**Comment by hannahsophiegr** [comment]
Ist das daduruch, wie wir es in die Mindmap geschrieben haben für euch geklärt, oder sollen wir noch genauer besprechen was passiert, zum Beispiel irgendwelche Fehlermeldungen oder ähnliches haben wir noch nicht implementiert oder?

**Comment by hannahsophiegr** [comment]
Beziehungsweise gehört das dann eher zum Issue Konversatuon oder

**Comment by hannahsophiegr** [comment]
ist fertig

**Comment by lauradax** [comment]
sieht gut aus!
