### ISSUE TITLE
Charakter/Konversation

### ISSUE THREAD

**Issue by lauradax** [ID-Start-Winter22/Turbo#11]
in der aktuellen Version ist die Kommunikation hilfreich, allerdings ein wenig trocken. In den weiteren schritten sollte Turbo etwas freundlicher bzw. motivierter wirken, sodass sich das Interesse an den Aktivitäten auch auf den/die User:in überträgt.

**Comment by tsontheimer** [comment]
Chatbot Umgangssprache wurde überarbeitet

**Comment by lauradax** [comment]
ich habe auch nochmal ein paar Kommunikationsbausteine bearbeitet, sodass sie etwas besser zum character passen

**Comment by lauradax** [comment]
Kommunikation wurde angepasst, fühlt sich menschlicher an. Im Anschluss sollten wir in Sprint 2 in die breite gehen
