### ISSUE TITLE
Chatbot Funktionalität weiter entwickeln

### ISSUE THREAD

**Issue by hannahsophiegr** [ID-Start-Winter22/Turbo#15]
Im Prinzip beinhaltet die Aufgabe alles, was mit dem Programmieren zu hat von dem Chatbot, wir können des gerne noch weiter unterteilen, aber hätte es jetzt erstmal so aufgeschrieben, hängt ja bisschen davon ab was wir in den anderen Issues besprechen

**Comment by tsontheimer** [comment]
Buttons zur Auswahl für die Nutzereingabe wurden hinzugefügt

**Comment by lauradax** [comment]
Wir haben buttons und eine bessere konversation, das ist ja schon mal was. alles weitere in sprint 2
