### ISSUE TITLE
Hintergrundbild , Banner und Bild von uns

### ISSUE THREAD

**Issue by hannahsophiegr** [ID-Start-Winter22/Turbo#16]

**Comment by hannahsophiegr** [comment]
Wie weit seid ihr damit schon, also was habt ihr bislang schon

**Comment by hannahsophiegr** [comment]
Props auf jeden Fall an die Wikistartseite, sieht echt super gut aus

**Comment by lauradax** [comment]
> Wie weit seid ihr damit schon, also was habt ihr bislang schon

ich hab vorhin was in illustrator zusammengebastelt, bin aber noch nicht ganz happy damit
