### ISSUE TITLE
Chatbot reagiert nicht

### ISSUE THREAD

**Issue by tsontheimer** [ID-Start-Winter22/Turbo#18]
Sobald der Chatbot als Instance über AWS gestartet und verbunden wird, ist dieser zwar mit Icon etc. zugänglich, reagiert aber nicht auf  jeglichen Anfragen des Nutzers wie "Hallo", "Was machen".

**Comment by lauradax** [comment]
ähhhh okay....was genau wurde geändert? laufen vorherige Versionen?

**Comment by tsontheimer** [comment]
Ja nix. Man müsste das GitHub repository Klonen, den lokalen Chatbot mit AWS über SSH-Client mit der Instance verbinden, dass auf http://34.251.35.212/ sich was tut. 

https://eu-west-1.console.aws.amazon.com/ec2/home?region=eu-west-1#ConnectToInstance:instanceId=i-0913fa7cbfcd8f576

**Comment by hannahsophiegr** [comment]
habt ihr das gemacht, also läuft der jetzt über des aws?

**Comment by tsontheimer** [comment]
Wir habens auf Teufel komm raus probiert, allerdings ohne Erfolg. Michael Eggers weiss auch nicht weiter, meinte aber wir haben uns gut geschlagen und er würde sich das Problem aufschreiben. Wir können derweil alles Lokal weiter machen und später dann mit AWS.

<a href="https://ibb.co/mBmMBpv"><img src="https://i.ibb.co/8BJSBkz/Screenshot-2022-12-15-153701.png" alt="Screenshot-2022-12-15-153701" border="0"></a>

**Comment by hannahsophiegr** [comment]
hatte sich, da kein aws mehr erledigt
