### ISSUE TITLE
Personas im Wiki klickbar machen

### ISSUE THREAD

**Issue by hannahsophiegr** [ID-Start-Winter22/Turbo#20]
Hatten sie uns beim letzten mal angemerkt

**Comment by hannahsophiegr** [comment]
Weiß jemand wie das geht?

**Comment by tsontheimer** [comment]
Sind mit Personas die gezeichneten Bilder von uns gemeint? Wenn ja könnte man über HTML die Bilder einzeln in einer "Tabelle" und mit einem "Bild-Hyperlink" verknüpfen, sodass jeder anklick- und vergrößerbar ist.

**Comment by hannahsophiegr** [comment]
ne sind die befragten Personen, die wir erstellen sollten, des sind einfach screenshots vom Miro Board

**Comment by hannahsophiegr** [comment]
hab jetzt wenn man auf das Bild klickt, ein Link zu der Ansicht auf dem Miro-Board eingefüht

**Comment by hannahsophiegr** [comment]
Funkitoniert
