### ISSUE TITLE
Öffentliche IPv4-Adresse ändert sich

### ISSUE THREAD

**Issue by tsontheimer** [ID-Start-Winter22/Turbo#22]
Nach jedem stoppen und wieder starten der Instance ändert sich die Öffentliche Zugangsadresse des Chatbots. Optimal und einfachheitshalber wäre eine konstante Zugangsadresse mit selbst ausgewählten Namen.

**Comment by lauradax** [comment]
weisst du wie man das machen kann und wie die dann auszusehen hat?

**Comment by tsontheimer** [comment]
Elastic IP ist nun 34.251.35.212. Öffentliche IPv4 Adresse ist somit statisch und immer über die selbe öffentliche Zugangsadresse erreichbar, auch nach stoppen und starten der Instance.
