### ISSUE TITLE
blender Maskottchen

### ISSUE THREAD

**Issue by lauradax** [ID-Start-Winter22/Turbo#23]
wollen wir dieses 3d model was ich erstellt habe irgendwo einbinden? ich find es irgendwie süsser als das bisherige logo, allerdings wäre das ein großer Bruch was das design angeht also müssten wir das nochmal diskutieren. Ich persönlich fände das 3d Maskottchen etwas mehr approachable was für die Entwicklung eines Charakters wichtig ist. 
![Image 13 12 22 at 10 57](https://user-images.githubusercontent.com/116880483/207292996-c0581a7e-ae6b-4a61-9923-c96b7e6a98e2.JPG)

**Comment by lauradax** [comment]
@tsontheimer @Mashto-o @Yeva1 @hannahsophiegr schreibt mal bitte einen kommentar wie ihr das findet!

**Comment by hannahsophiegr** [comment]
Ich fänds eigentlich ganz cool, wir haben ja doch eher einen Chatbot, der motivieren soll und auch selber irgendwie so aussehen soll als würde er viel rum kommen, und so hat er einfach mehr Charakter

**Comment by tsontheimer** [comment]
Finde ich eine klasse Idee und optisch auch passend gestaltet. Allerdings fällt mir jetzt gerade keinen konkreten Weg ein 3D-Model zu implementieren. Ich glaub kann man über JavaScript das 3D technisch auf der GitHub WikiSeite darstellen.

**Comment by lauradax** [comment]
@tsontheimer man kann einen render ja auch als png o.ä exportieren. rendern kann ich das bild in jeglichem winkel den wir brauchen

**Comment by tsontheimer** [comment]
@lauradax Ah super. Fände ich Klasse wenn wir das so machen.

**Comment by Mashto-o** [comment]
Ich finde diese Schnecke sehr süß. Ich werde gerne mit dir eine Geschichte machen.
