### ISSUE TITLE
Slogan als Tag

### ISSUE THREAD

**Issue by tsontheimer** [ID-Start-Winter22/Turbo#25]
Auf der Startseite unserer AWS Instance steht nach der öffentliche IPv4-Adresse momentan noch das hier: <a href="https://imgbb.com/"><img src="https://i.ibb.co/SrpVKyr/32343dds.png" alt="32343dds" border="0"></a><br /><a target='_blank' href='https://de.imgbb.com/'></a><br />

Hat jemand einen Slogan oder andere Vorschläge, statt "add slogan here"

**Comment by lauradax** [comment]
OMG AWWWW WIE SÜSSSSSSS🥰🥰

**Comment by tsontheimer** [comment]
> turbo - auch eine Schnecke kann viel erleben! so als Anspielung darauf, dass auch wenn du faul bist und unmotiviert und man dadurch nur langsam voran kommt, kann man viel erleben, womit einem der chatbot hilft

Ok ist abgeändert.

**Comment by lauradax** [comment]
dann muss das auch im code in der vorstellung des bots geändert werden!
