### ISSUE TITLE
blender turbo

### ISSUE THREAD

**Issue by lauradax** [ID-Start-Winter22/Turbo#27]
das logo/maskottchen ist zwar wie es ist echt cute, ein paar sachen könnten aber noch verbessert werden. der feinschliff fehlt also.

**Comment by lauradax** [comment]
![92B9EC78-68ED-40B3-8BDC-7E934DE8E354](https://user-images.githubusercontent.com/116880483/208039215-a3237e8b-b1d5-4a86-bdbd-28f14184fa74.png)

- kopf ist ein bisschen eingedellt
- rucksack ist recht rudimentär gemodelt
- augen/fühler brauchen subdevision 
- mund anders modellieren als aus torus
- problem mit render-quality fixen

**Comment by hannahsophiegr** [comment]
Fertig!

**Comment by lauradax** [comment]
modell ist jz ein bisschen dicker, augen und mund haben subdivision 

kopf zwar immenroch flach aber nicht dellig

**Comment by lauradax** [comment]
> Fertig!

danke fürs issue schliessen und pngs hochladen, hätte ich vergessen zu machen 😳
