### ISSUE TITLE
Hintergrund für Website Ideensammlung

### ISSUE THREAD

**Issue by lauradax** [ID-Start-Winter22/Turbo#28]
Aktuell ist das ein ziemlicher Prototyp. Es ist etwas aber ich bin nicht happy damit…werde ich entsprechend nochmal überarbeiten und damit ein rundes branding schaffen

**Comment by hannahsophiegr** [comment]
Ich würde da auch ganz gerne mitmachen :)

**Comment by hannahsophiegr** [comment]
ich hab einige Ideen gesammelt, muss sie allerdings noch Final umwandeln
